# Generated by Django 5.1.2 on 2025-04-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post", models.CharField(max_length=60)),
                ("comment", models.TextField(max_length=300)),
                ("datetime", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="FriendRequestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=60)),
                ("friendname", models.CharField(max_length=100)),
                ("datetime", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="LikeOrDisLikeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post", models.CharField(max_length=60)),
                ("status", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="PostModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=60)),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=500)),
                ("tags", models.CharField(max_length=500)),
                ("image", models.FileField(upload_to="images")),
                ("datetime", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RegistrationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("mobile", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("pic", models.FileField(upload_to="images")),
                ("gender", models.CharField(max_length=50)),
                ("dob", models.CharField(max_length=50)),
                ("interests", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ShareModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=60)),
                ("post", models.CharField(max_length=60)),
            ],
        ),
    ]
